---
title: "Blood Rhesus"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load datas

```{r , fig.width=13,fig.height=12}
library(stringr)
id <- c("O-", "O+", "B-", "B+", "A-", "A+", "AB-", "AB+")

## 
get_groupe <- function(agroupe){
  out <- ""
  out <- str_replace_all(agroupe, "[^[:alnum:]]", "")

  return(out)
}

#test <- get_groupe("AB-")
#test
groupe <- lapply(id, get_groupe)
groupe

# get rhesus
get_rhesus <- function(agroupe){
  if(grepl('-', agroupe)){
    return("Rh-")
  } else {
    return("Rh+")
  }
}
#test <- get_rhesus("AB+")
#test
#test <- get_rhesus("O-")
#test
rhesus <- lapply(id, get_rhesus)
rhesus

rate <- c(7,39, 1.5, 7.5, 6, 36, 0.5, 2.5)
rate

# buidl the data frame
nodes <- cbind(id, groupe, rhesus, rate)
nodes

## now, build the edges
edges <- cbind(c("O-", "O-", "O-","O-","O-","O-","O-","O-", "O+","O+","O+","O+","B-","B-","B-","B-","B+","B+","A-","A-","A-","A-","A+","A+","AB-","AB-","AB+"),
          c("AB+","AB-","A+","A-","B+","B-","O+","O-","AB+","A+","B+","O+","AB+","AB-","B+","B-","AB+","B+", "AB+", "AB-", "A+", "A-", "AB+", "A+", "AB+", "AB-", "AB+"))
edges

## build a first graph
library(igraph)
net <- graph_from_data_frame(d=edges, vertices=nodes, directed=T) 
V(net)$size <- degree(net, mode = "in")*3

plot(net,
     edge.arrow.size=.4,
     vertex.label.dist=3,
     #vertex.label=NA,
     
     layout=layout.fruchterman.reingold
     )

## circular
plot(net,
     edge.arrow.size=.7,
     vertex.label.dist=3,
     ##vertex.label=NA,
     layout=layout_in_circle
     )

#library("networkD3")
#networkData <- cbind(edges, nodes)
#simpleNetwork(as.data.frame(networkData))


```

## Echanges entre rhesus

```{r,echo=FALSE}
#edges
#class(edges)
rhesus_edges <- apply(edges, c(1,2), get_rhesus)
#rhesus_edges

rhesus_aggreg <- data.frame(rhesus_edges)
rhesus_aggreg["weight"] <- 1
#rhesus_aggreg

weighted_rhesus_edges <- aggregate(rhesus_aggreg[c("weight")], by=list(rhesus_from=rhesus_aggreg$X1, rhesus_to=rhesus_aggreg$X2), FUN=sum, na.rm=TRUE)
#weighted_rhesus_edges

#class(rhesus)
unique_rhesus <- unique(weighted_rhesus_edges$rhesus_from)
# now plot relations between rhesus
net <- graph_from_data_frame(d=weighted_rhesus_edges, vertices=unique_rhesus, directed=T) 
V(net)$size <- degree(net, mode = "in")*5
#E(net)$weight <- weighted_rhesus_edges$weight

plot(net, edge.arrow.size=.4,
     vertex.label.dist=3,
     #vertex.label=NA,
     layout=layout.fruchterman.reingold)




#library("networkD3")
#networkData <- cbind(weighted_rhesus_edges$rhesus_from, weighted_rhesus_edges$rhesus_to)
#simpleNetwork(as.data.frame(networkData))

```

